"use strict";
// src/routes/crm-outlook.js

const express         = require("express");
const router          = express.Router();
const { pool }        = require("../config/database");
const { requireAuth, requireSuperAdmin } = require("../middleware/auth");
const { crmAuth }     = require("../middleware/crm-rbac");
const outlookService  = require("../services/outlookService");
const config          = require("../config");
const { v4: uuidv4 }  = require("uuid");
const { requireActiveEmailProvider, resolveProviderGate } = require("../middleware/email-provider");

// Guards connect/send/sync actions — blocks them unless this tenant's active
// provider is 'outlook' (bypassed automatically for crm_training_mode tenants).
const outlookGate = requireActiveEmailProvider("outlook");

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

async function resolvePartner(rawId, tenantId) {
  if (UUID_RE.test(String(rawId))) {
    const { rows } = await pool.query(
      "SELECT id, company FROM crm_partners WHERE id = $1 AND tenant_id = $2", [rawId, tenantId]
    );
    return rows[0] ?? null;
  }
  const num = parseInt(rawId);
  if (isNaN(num)) return null;
  const { rows } = await pool.query(
    "SELECT id, company FROM crm_partners WHERE dwh_partner_id = $1 AND tenant_id = $2", [num, tenantId]
  );
  return rows[0] ?? null;
}

// ═══════════════════════════════════════════════════════════════════════════════
// OAUTH2
// ═══════════════════════════════════════════════════════════════════════════════

// Company mailbox connect/status/disconnect are super-admin-only actions,
// performed from Tenant → Email in the admin panel — never from a lead or
// partner view. tenantId is an explicit query param because the calling
// super admin manages an arbitrary tenant, not necessarily their own.
router.get("/oauth/url", requireAuth, requireSuperAdmin, async (req, res, next) => {
  try {
    const { tenantId } = req.query;
    if (!tenantId) return res.status(400).json({ error: "tenantId jest wymagany" });
    const gate = await resolveProviderGate(tenantId, "outlook");
    if (!gate.ok) {
      return res.status(gate.active ? 403 : 400).json({
        error: gate.active
          ? `Ta organizacja korzysta z innego dostawcy poczty (${gate.active}).`
          : "Outlook nie jest aktywnym providerem dla tego tenanta.",
        code: "PROVIDER_NOT_ACTIVE",
      });
    }
    const url = await outlookService.getTenantAuthUrl(tenantId, req.user.id);
    res.json({ url });
  } catch (err) { next(err); }
});

// No requireAuth — Microsoft redirects the browser without Authorization header.
// tenantId is encoded in the HMAC-signed state parameter generated by /oauth/url.
router.get("/oauth/callback", async (req, res) => {
  try {
    const { code, error, state } = req.query;
    if (error) return res.redirect(`${config.frontendUrl}/crm/outlook/callback?status=error&reason=${encodeURIComponent(error)}`);
    if (!code)  return res.redirect(`${config.frontendUrl}/crm/outlook/callback?status=error&reason=no_code`);
    if (!state) return res.redirect(`${config.frontendUrl}/crm/outlook/callback?status=error&reason=missing_state`);

    const parsed = outlookService.parseTenantOAuthState(state);
    if (!parsed) {
      return res.redirect(`${config.frontendUrl}/crm/outlook/callback?status=error&reason=invalid_state`);
    }
    const { tenantId, initiatingUserId } = parsed;

    const gate = await resolveProviderGate(tenantId, "outlook");
    if (!gate.ok) {
      return res.redirect(`${config.frontendUrl}/crm/outlook/callback?status=error&reason=provider_not_active`);
    }

    await outlookService.exchangeTenantCodeAndSave(code, tenantId, initiatingUserId);

    res.redirect(`${config.frontendUrl}/crm/outlook/callback?status=connected`);
  } catch (err) {
    console.error("[Outlook] OAuth callback error:", err.message);
    res.redirect(`${config.frontendUrl}/crm/outlook/callback?status=error&reason=callback_failed`);
  }
});

async function statusHandler(req, res) {
  try {
    const { tenantId } = req.query;
    if (!tenantId) return res.status(400).json({ error: "tenantId jest wymagany" });
    const status = await outlookService.getTenantMailboxStatus(tenantId);
    res.json(status);
  } catch (err) {
    res.status(500).json({ error: "Błąd serwera" });
  }
}
router.get("/status", requireAuth, requireSuperAdmin, statusHandler);

async function disconnectHandler(req, res) {
  try {
    const { tenantId } = req.query;
    if (!tenantId) return res.status(400).json({ error: "tenantId jest wymagany" });
    await outlookService.disconnectTenantMailbox(tenantId);
    res.json({ ok: true });
  } catch (err) {
    res.status(500).json({ error: "Błąd serwera" });
  }
}
router.delete("/oauth/disconnect", requireAuth, requireSuperAdmin, disconnectHandler);

// ═══════════════════════════════════════════════════════════════════════════════
// WYSYŁKA — LEAD
// ═══════════════════════════════════════════════════════════════════════════════

async function sendLeadHandler(req, res) {
  try {
    const leadId = parseInt(req.params.leadId);
    const { to, cc, subject, body, inReplyTo, references } = req.body;

    if (!to || !subject) {
      return res.status(400).json({ error: "Pola 'to' i 'subject' są wymagane" });
    }

    const leadQ = await pool.query(
      "SELECT id FROM crm_leads WHERE id = $1 AND tenant_id = $2",
      [leadId, req.tenantId],
    );
    if (!leadQ.rows.length) return res.status(404).json({ error: "Lead nie znaleziony" });

    const sent = await outlookService.sendTenantEmail({
      tenantId:  req.tenantId,
      userId:    req.user.id,
      to, cc: cc || null, subject,
      body:      body || "",
      inReplyTo: inReplyTo || null,
      references: references || null,
    });

    const actR = await pool.query(
      `INSERT INTO crm_lead_activities
         (lead_id, type, title, body, activity_at, gmail_thread_id, gmail_message_id,
          email_provider, created_by, is_read, tenant_id)
       VALUES ($1, 'email', $2, $3, NOW(), $4, $5, 'outlook', $6, true, $7)
       RETURNING id`,
      [leadId, subject, body || null, sent.threadId, sent.messageId, req.user.id, req.tenantId],
    );

    res.json({ messageId: sent.messageId, threadId: sent.threadId, activityId: actR.rows[0].id });
  } catch (err) {
    console.error("[Outlook] send/lead error:", err.message);
    if (err.code === "PROVIDER_NOT_CONFIGURED") {
      return res.status(err.status || 400).json({ error: err.message, code: err.code });
    }
    if (err.message?.includes("Brak połączonego konta")) {
      return res.status(401).json({ error: err.message });
    }
    res.status(500).json({ error: "Błąd wysyłki emaila: " + err.message });
  }
}
router.post("/send/lead/:leadId", requireAuth, crmAuth, outlookGate, sendLeadHandler);

// ═══════════════════════════════════════════════════════════════════════════════
// WYSYŁKA — PARTNER
// ═══════════════════════════════════════════════════════════════════════════════

async function sendPartnerHandler(req, res) {
  try {
    const { to, cc, subject, body, inReplyTo, references } = req.body;

    if (!to || !subject) {
      return res.status(400).json({ error: "Pola 'to' i 'subject' są wymagane" });
    }

    const partner = await resolvePartner(req.params.partnerId, req.tenantId);
    if (!partner) return res.status(404).json({ error: "Partner nie znaleziony" });

    const sent = await outlookService.sendTenantEmail({
      tenantId:  req.tenantId,
      userId:    req.user.id,
      to, cc: cc || null, subject,
      body:      body || "",
      inReplyTo: inReplyTo || null,
      references: references || null,
    });

    const actR = await pool.query(
      `INSERT INTO crm_partner_activities
         (partner_id, type, title, body, activity_at, gmail_thread_id, gmail_message_id,
          email_provider, created_by, is_read, tenant_id)
       VALUES ($1, 'email', $2, $3, NOW(), $4, $5, 'outlook', $6, true, $7)
       RETURNING id`,
      [partner.id, subject, body || null, sent.threadId, sent.messageId, req.user.id, req.tenantId],
    );

    res.json({ messageId: sent.messageId, threadId: sent.threadId, activityId: actR.rows[0].id });
  } catch (err) {
    console.error("[Outlook] send/partner error:", err.message);
    if (err.code === "PROVIDER_NOT_CONFIGURED") {
      return res.status(err.status || 400).json({ error: err.message, code: err.code });
    }
    if (err.message?.includes("Brak połączonego konta")) {
      return res.status(401).json({ error: err.message });
    }
    res.status(500).json({ error: "Błąd wysyłki emaila: " + err.message });
  }
}
router.post("/send/partner/:partnerId", requireAuth, crmAuth, outlookGate, sendPartnerHandler);

// ═══════════════════════════════════════════════════════════════════════════════
// WĄTEK — LEAD
// ═══════════════════════════════════════════════════════════════════════════════

async function threadLeadHandler(req, res) {
  try {
    const leadId         = parseInt(req.params.leadId);
    const conversationId = req.params.conversationId;
    const messages       = await outlookService.getTenantThread(req.tenantId, conversationId);

    const msgIds = messages.map(m => m.id);
    if (msgIds.length) {
      const { rows: outRows } = await pool.query(
        `SELECT id AS activity_id, gmail_message_id FROM crm_lead_activities
         WHERE lead_id = $1 AND gmail_message_id = ANY($2) AND tenant_id = $3`,
        [leadId, msgIds, req.tenantId],
      );
      const outIds = new Set(outRows.map(r => r.gmail_message_id));

      const { rows: readRows } = await pool.query(
        `SELECT gmail_message_id, is_read FROM crm_email_message_reads
         WHERE gmail_message_id = ANY($1) AND tenant_id = $2`,
        [msgIds, req.tenantId],
      );
      const readMap = Object.fromEntries(readRows.map(r => [r.gmail_message_id, r.is_read]));

      for (const msg of messages) {
        if (outIds.has(msg.id)) {
          msg.is_read    = true;
          msg.created_by = "outgoing";
          msg.activity_id = outRows.find(r => r.gmail_message_id === msg.id)?.activity_id ?? null;
        } else {
          msg.is_read    = readMap[msg.id] ?? false;
          msg.created_by = null;
          msg.activity_id = null;
        }
      }

      // Mark thread activity as read on open
      pool.query(
        `UPDATE crm_lead_activities SET is_read = true, updated_at = NOW()
         WHERE lead_id = $1 AND gmail_thread_id = $2 AND type = 'email' AND is_read = false AND tenant_id = $3`,
        [leadId, conversationId, req.tenantId],
      ).catch(() => {});
    }

    res.set('Cache-Control', 'no-store, no-cache, must-revalidate');
    res.json(messages);
  } catch (err) {
    console.error("[Outlook] getThread/lead error:", err.message);
    res.status(500).json({ error: "Błąd pobierania wątku: " + err.message });
  }
}
router.get("/thread/lead/:leadId/:conversationId", requireAuth, crmAuth, threadLeadHandler);

// ═══════════════════════════════════════════════════════════════════════════════
// WĄTEK — PARTNER
// ═══════════════════════════════════════════════════════════════════════════════

async function threadPartnerHandler(req, res) {
  try {
    const conversationId = req.params.conversationId;
    const resolved       = await resolvePartner(req.params.partnerId, req.tenantId);
    const partnerId      = resolved?.id ?? req.params.partnerId;
    const messages       = await outlookService.getTenantThread(req.tenantId, conversationId);

    const msgIds = messages.map(m => m.id);
    if (msgIds.length) {
      const { rows: outRows } = await pool.query(
        `SELECT id AS activity_id, gmail_message_id FROM crm_partner_activities
         WHERE partner_id = $1 AND gmail_message_id = ANY($2) AND tenant_id = $3`,
        [partnerId, msgIds, req.tenantId],
      );
      const outIds = new Set(outRows.map(r => r.gmail_message_id));

      const { rows: readRows } = await pool.query(
        `SELECT gmail_message_id, is_read FROM crm_email_message_reads
         WHERE gmail_message_id = ANY($1) AND tenant_id = $2`,
        [msgIds, req.tenantId],
      );
      const readMap = Object.fromEntries(readRows.map(r => [r.gmail_message_id, r.is_read]));

      for (const msg of messages) {
        if (outIds.has(msg.id)) {
          msg.is_read    = true;
          msg.created_by = "outgoing";
          msg.activity_id = outRows.find(r => r.gmail_message_id === msg.id)?.activity_id ?? null;
        } else {
          msg.is_read    = readMap[msg.id] ?? false;
          msg.created_by = null;
          msg.activity_id = null;
        }
      }

      pool.query(
        `UPDATE crm_partner_activities SET is_read = true, updated_at = NOW()
         WHERE partner_id = $1 AND gmail_thread_id = $2 AND type = 'email' AND is_read = false AND tenant_id = $3`,
        [partnerId, conversationId, req.tenantId],
      ).catch(() => {});
    }

    res.set('Cache-Control', 'no-store, no-cache, must-revalidate');
    res.json(messages);
  } catch (err) {
    console.error("[Outlook] getThread/partner error:", err.message);
    res.status(500).json({ error: "Błąd pobierania wątku: " + err.message });
  }
}
router.get("/thread/partner/:partnerId/:conversationId", requireAuth, crmAuth, threadPartnerHandler);

// ═══════════════════════════════════════════════════════════════════════════════
// DEBUG — ręczne sprawdzenie nowych wiadomości przez delta query
// POST /api/crm/outlook/debug/process
// ═══════════════════════════════════════════════════════════════════════════════

async function debugProcessHandler(req, res) {
  try {
    const { rows } = await pool.query(
      "SELECT email, delta_link FROM tenant_outlook_tokens WHERE tenant_id = $1",
      [req.tenantId],
    );
    if (!rows.length) return res.status(404).json({ error: "Brak podłączonej skrzynki firmowej Outlook" });

    const { email, delta_link } = rows[0];

    const { deltaLink, newMessages } = await outlookService.getTenantNewMessages(req.tenantId);

    const note = !delta_link
      ? "delta_link był pusty — ustawiono bazowy punkt. Wyślij do siebie email i kliknij ponownie."
      : null;

    res.json({
      ok: true,
      email,
      note,
      deltaLink_initialized: !delta_link,
      newMessages_found: newMessages.length,
      newMessages: newMessages.slice(0, 10).map(m => ({
        id:             m.id,
        subject:        m.subject,
        from:           m.from?.emailAddress?.address,
        conversationId: m.conversationId,
        receivedAt:     m.receivedDateTime,
      })),
    });
  } catch (err) {
    console.error("[Outlook] debug/process error:", err.message);
    const status = err.code === "PROVIDER_NOT_CONFIGURED" ? (err.status || 400) : 500;
    res.status(status).json({ error: err.message, ...(err.code ? { code: err.code } : {}) });
  }
}
router.post("/debug/process", requireAuth, crmAuth, outlookGate, debugProcessHandler);

// Handlers reused by the unified /api/crm/email dispatcher (crm-email.js).
// status/disconnect/connect are super-admin-only tenant-mailbox actions now
// (see /status, /oauth/url, /oauth/disconnect above) and are not part of the
// regular-user dispatcher surface, so they are not exposed here.
router.handlers = {
  sendLead:      sendLeadHandler,
  sendPartner:   sendPartnerHandler,
  threadLead:    threadLeadHandler,
  threadPartner: threadPartnerHandler,
  debugProcess:  debugProcessHandler,
};

module.exports = router;
