"use strict";
// src/routes/crm-zoho.js

const express        = require("express");
const router         = express.Router();
const { pool }       = require("../config/database");
const { requireAuth } = require("../middleware/auth");
const { crmAuth }    = require("../middleware/crm-rbac");
const zohoService    = require("../services/zohoService");
const config         = require("../config");

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

async function resolvePartner(rawId, tenantId) {
  if (UUID_RE.test(String(rawId))) {
    const { rows } = await pool.query(
      "SELECT id, company FROM crm_partners WHERE id = $1 AND tenant_id = $2", [rawId, tenantId],
    );
    return rows[0] ?? null;
  }
  const num = parseInt(rawId);
  if (isNaN(num)) return null;
  const { rows } = await pool.query(
    "SELECT id, company FROM crm_partners WHERE dwh_partner_id = $1 AND tenant_id = $2", [num, tenantId],
  );
  return rows[0] ?? null;
}

// ═══════════════════════════════════════════════════════════════════════════════
// OAUTH2
// ═══════════════════════════════════════════════════════════════════════════════

router.get("/oauth/url", requireAuth, async (req, res, next) => {
  try {
    const url = await zohoService.getAuthUrl(req.user.id);
    res.json({ url });
  } catch (err) { next(err); }
});

// No requireAuth — Zoho redirects the browser without Authorization header.
// User ID is encoded in the HMAC-signed state parameter generated by /oauth/url.
// Zoho passes accounts-server (DC-specific token endpoint) and location in callback.
router.get("/oauth/callback", async (req, res) => {
  try {
    const { code, error, state } = req.query;
    const accountsServer = req.query["accounts-server"] || req.query.accounts_server || "";

    if (error) {
      return res.redirect(`${config.frontendUrl}/crm/zoho/callback?status=error&reason=${encodeURIComponent(error)}`);
    }
    if (!code) {
      return res.redirect(`${config.frontendUrl}/crm/zoho/callback?status=error&reason=no_code`);
    }
    if (!state) {
      return res.redirect(`${config.frontendUrl}/crm/zoho/callback?status=error&reason=missing_state`);
    }
    if (!accountsServer) {
      return res.redirect(`${config.frontendUrl}/crm/zoho/callback?status=error&reason=missing_accounts_server`);
    }

    const userId = zohoService.parseOAuthState(state);
    if (!userId) {
      return res.redirect(`${config.frontendUrl}/crm/zoho/callback?status=error&reason=invalid_state`);
    }

    await zohoService.exchangeCodeAndSave(code, userId, accountsServer);

    res.redirect(`${config.frontendUrl}/crm/zoho/callback?status=connected`);
  } catch (err) {
    console.error("[Zoho] OAuth callback error:", err.message);
    res.redirect(`${config.frontendUrl}/crm/zoho/callback?status=error&reason=callback_failed`);
  }
});

router.get("/status", requireAuth, async (req, res) => {
  try {
    const status = await zohoService.getStatus(req.user.id);
    res.json(status);
  } catch (err) {
    res.status(500).json({ error: "Błąd serwera" });
  }
});

router.delete("/oauth/disconnect", requireAuth, async (req, res) => {
  try {
    await zohoService.disconnect(req.user.id);
    res.json({ ok: true });
  } catch (err) {
    res.status(500).json({ error: "Błąd serwera" });
  }
});

// ═══════════════════════════════════════════════════════════════════════════════
// WYSYŁKA — LEAD
// ═══════════════════════════════════════════════════════════════════════════════

router.post("/send/lead/:leadId", requireAuth, crmAuth, async (req, res) => {
  try {
    const leadId = parseInt(req.params.leadId);
    const { to, cc, subject, body, inReplyTo, threadId: callerThreadId } = req.body;

    if (!to || !subject) {
      return res.status(400).json({ error: "Pola 'to' i 'subject' są wymagane" });
    }

    const leadQ = await pool.query(
      "SELECT id FROM crm_leads WHERE id = $1 AND tenant_id = $2",
      [leadId, req.tenantId],
    );
    if (!leadQ.rows.length) return res.status(404).json({ error: "Lead nie znaleziony" });

    // Verify caller-supplied threadId belongs to this lead/tenant and is a Zoho thread
    let verifiedActivity = null;
    if (inReplyTo && callerThreadId) {
      const actQ = await pool.query(
        `SELECT id, gmail_thread_id FROM crm_lead_activities
         WHERE lead_id = $1 AND gmail_thread_id = $2
           AND email_provider = 'zoho' AND tenant_id = $3 AND type = 'email'
         LIMIT 1`,
        [leadId, String(callerThreadId), req.tenantId],
      );
      verifiedActivity = actQ.rows[0] || null;
    }

    const sent = await zohoService.sendEmail({
      userId: req.user.id,
      to, cc: cc || null, subject,
      body:      body || "",
      inReplyTo: inReplyTo || null,
    });

    if (verifiedActivity) {
      // Reply to a known thread — update the existing activity timestamp, no new card
      await pool.query(
        `UPDATE crm_lead_activities SET activity_at = NOW(), updated_at = NOW() WHERE id = $1`,
        [verifiedActivity.id],
      );
      return res.json({
        messageId:  sent.messageId,
        threadId:   verifiedActivity.gmail_thread_id,
        activityId: verifiedActivity.id,
      });
    }

    // New message or reply to an unknown thread — insert a new activity
    // For replies with no verified threadId, prefer Zoho's threadId over everything.
    // If Zoho also returned null (no threadId for reply), use callerThreadId as last resort.
    const threadIdToSave = sent.threadId || callerThreadId || sent.messageId;
    const actR = await pool.query(
      `INSERT INTO crm_lead_activities
         (lead_id, type, title, body, activity_at, gmail_thread_id, gmail_message_id,
          email_provider, created_by, is_read, tenant_id)
       VALUES ($1, 'email', $2, $3, NOW(), $4, $5, 'zoho', $6, true, $7)
       RETURNING id`,
      [leadId, subject, body || null, threadIdToSave, sent.messageId, req.user.id, req.tenantId],
    );

    res.json({ messageId: sent.messageId, threadId: threadIdToSave, activityId: actR.rows[0].id });
  } catch (err) {
    console.error("[Zoho] send/lead error:", err.message);
    if (err.message?.includes("Brak połączonego konta")) {
      return res.status(401).json({ error: err.message });
    }
    res.status(500).json({ error: "Błąd wysyłki emaila: " + err.message });
  }
});

// ═══════════════════════════════════════════════════════════════════════════════
// WYSYŁKA — PARTNER
// ═══════════════════════════════════════════════════════════════════════════════

router.post("/send/partner/:partnerId", requireAuth, crmAuth, async (req, res) => {
  try {
    const { to, cc, subject, body, inReplyTo, threadId: callerThreadId } = req.body;

    if (!to || !subject) {
      return res.status(400).json({ error: "Pola 'to' i 'subject' są wymagane" });
    }

    const partner = await resolvePartner(req.params.partnerId, req.tenantId);
    if (!partner) return res.status(404).json({ error: "Partner nie znaleziony" });

    // Verify caller-supplied threadId belongs to this partner/tenant and is a Zoho thread
    let verifiedActivity = null;
    if (inReplyTo && callerThreadId) {
      const actQ = await pool.query(
        `SELECT id, gmail_thread_id FROM crm_partner_activities
         WHERE partner_id = $1 AND gmail_thread_id = $2
           AND email_provider = 'zoho' AND tenant_id = $3 AND type = 'email'
         LIMIT 1`,
        [partner.id, String(callerThreadId), req.tenantId],
      );
      verifiedActivity = actQ.rows[0] || null;
    }

    const sent = await zohoService.sendEmail({
      userId: req.user.id,
      to, cc: cc || null, subject,
      body:      body || "",
      inReplyTo: inReplyTo || null,
    });

    if (verifiedActivity) {
      // Reply to a known thread — update the existing activity timestamp, no new card
      await pool.query(
        `UPDATE crm_partner_activities SET activity_at = NOW(), updated_at = NOW() WHERE id = $1`,
        [verifiedActivity.id],
      );
      return res.json({
        messageId:  sent.messageId,
        threadId:   verifiedActivity.gmail_thread_id,
        activityId: verifiedActivity.id,
      });
    }

    // New message or reply to an unknown thread — insert a new activity
    const threadIdToSave = sent.threadId || callerThreadId || sent.messageId;
    const actR = await pool.query(
      `INSERT INTO crm_partner_activities
         (partner_id, type, title, body, activity_at, gmail_thread_id, gmail_message_id,
          email_provider, created_by, is_read, tenant_id)
       VALUES ($1, 'email', $2, $3, NOW(), $4, $5, 'zoho', $6, true, $7)
       RETURNING id`,
      [partner.id, subject, body || null, threadIdToSave, sent.messageId, req.user.id, req.tenantId],
    );

    res.json({ messageId: sent.messageId, threadId: threadIdToSave, activityId: actR.rows[0].id });
  } catch (err) {
    console.error("[Zoho] send/partner error:", err.message);
    if (err.message?.includes("Brak połączonego konta")) {
      return res.status(401).json({ error: err.message });
    }
    res.status(500).json({ error: "Błąd wysyłki emaila: " + err.message });
  }
});

// ═══════════════════════════════════════════════════════════════════════════════
// WĄTEK — LEAD
// ═══════════════════════════════════════════════════════════════════════════════

router.get("/thread/lead/:leadId/:threadId", requireAuth, crmAuth, async (req, res) => {
  try {
    const leadId   = parseInt(req.params.leadId);
    const threadId = req.params.threadId;
    const messages = await zohoService.getThread(req.user.id, threadId);
    console.log(`[Zoho] getThread lead=${leadId} threadId=${threadId} → ${messages.length} wiadomości`);

    const msgIds = messages.map(m => m.id);
    if (msgIds.length) {
      const { rows: outRows } = await pool.query(
        `SELECT id AS activity_id, gmail_message_id FROM crm_lead_activities
         WHERE lead_id = $1 AND gmail_message_id = ANY($2) AND tenant_id = $3`,
        [leadId, msgIds, req.tenantId],
      );
      const outIds = new Set(outRows.map(r => r.gmail_message_id));

      const { rows: readRows } = await pool.query(
        `SELECT gmail_message_id, is_read FROM crm_email_message_reads
         WHERE gmail_message_id = ANY($1) AND tenant_id = $2`,
        [msgIds, req.tenantId],
      );
      const readMap = Object.fromEntries(readRows.map(r => [r.gmail_message_id, r.is_read]));

      for (const msg of messages) {
        const isKnownOutgoing = outIds.has(msg.id) || msg.isOutgoing === true;
        if (isKnownOutgoing) {
          msg.is_read     = true;
          msg.created_by  = "outgoing";
          msg.activity_id = outRows.find(r => r.gmail_message_id === msg.id)?.activity_id ?? null;
        } else {
          msg.is_read     = readMap[msg.id] ?? false;
          msg.created_by  = null;
          msg.activity_id = null;
        }
      }

      pool.query(
        `UPDATE crm_lead_activities SET is_read = true, updated_at = NOW()
         WHERE lead_id = $1 AND gmail_thread_id = $2 AND type = 'email' AND is_read = false AND tenant_id = $3`,
        [leadId, threadId, req.tenantId],
      ).catch(() => {});
    }

    res.set('Cache-Control', 'no-store, no-cache, must-revalidate');
    res.json(messages);
  } catch (err) {
    console.error("[Zoho] getThread/lead error:", err.message);
    res.status(500).json({ error: "Błąd pobierania wątku: " + err.message });
  }
});

// ═══════════════════════════════════════════════════════════════════════════════
// WĄTEK — PARTNER
// ═══════════════════════════════════════════════════════════════════════════════

router.get("/thread/partner/:partnerId/:threadId", requireAuth, crmAuth, async (req, res) => {
  try {
    const threadId = req.params.threadId;
    const resolved = await resolvePartner(req.params.partnerId, req.tenantId);
    const partnerId = resolved?.id ?? req.params.partnerId;
    const messages  = await zohoService.getThread(req.user.id, threadId);
    console.log(`[Zoho] getThread partner=${partnerId} threadId=${threadId} → ${messages.length} wiadomości`);

    const msgIds = messages.map(m => m.id);
    if (msgIds.length) {
      const { rows: outRows } = await pool.query(
        `SELECT id AS activity_id, gmail_message_id FROM crm_partner_activities
         WHERE partner_id = $1 AND gmail_message_id = ANY($2) AND tenant_id = $3`,
        [partnerId, msgIds, req.tenantId],
      );
      const outIds = new Set(outRows.map(r => r.gmail_message_id));

      const { rows: readRows } = await pool.query(
        `SELECT gmail_message_id, is_read FROM crm_email_message_reads
         WHERE gmail_message_id = ANY($1) AND tenant_id = $2`,
        [msgIds, req.tenantId],
      );
      const readMap = Object.fromEntries(readRows.map(r => [r.gmail_message_id, r.is_read]));

      for (const msg of messages) {
        const isKnownOutgoing = outIds.has(msg.id) || msg.isOutgoing === true;
        if (isKnownOutgoing) {
          msg.is_read     = true;
          msg.created_by  = "outgoing";
          msg.activity_id = outRows.find(r => r.gmail_message_id === msg.id)?.activity_id ?? null;
        } else {
          msg.is_read     = readMap[msg.id] ?? false;
          msg.created_by  = null;
          msg.activity_id = null;
        }
      }

      pool.query(
        `UPDATE crm_partner_activities SET is_read = true, updated_at = NOW()
         WHERE partner_id = $1 AND gmail_thread_id = $2 AND type = 'email' AND is_read = false AND tenant_id = $3`,
        [partnerId, threadId, req.tenantId],
      ).catch(() => {});
    }

    res.set('Cache-Control', 'no-store, no-cache, must-revalidate');
    res.json(messages);
  } catch (err) {
    console.error("[Zoho] getThread/partner error:", err.message);
    res.status(500).json({ error: "Błąd pobierania wątku: " + err.message });
  }
});

// ═══════════════════════════════════════════════════════════════════════════════
// RĘCZNE SPRAWDZENIE NOWYCH WIADOMOŚCI
// POST /api/crm/zoho/debug/process
// ═══════════════════════════════════════════════════════════════════════════════

router.post("/debug/process", requireAuth, crmAuth, async (req, res) => {
  try {
    const { rows } = await pool.query(
      "SELECT email, last_fetched_at FROM user_zoho_tokens WHERE user_id = $1",
      [req.user.id],
    );
    if (!rows.length) return res.status(404).json({ error: "Brak połączonego konta Zoho" });

    const { email } = rows[0];
    const { newMessages } = await zohoService.getNewMessages(req.user.id);

    res.json({
      ok: true,
      email,
      newMessages_found: newMessages.length,
      newMessages: newMessages.slice(0, 10).map(m => ({
        id:         String(m.messageId),
        subject:    m.subject,
        from:       m.fromAddress,
        threadId:   String(m.threadId || m.messageId),
        receivedAt: new Date(parseInt(m.receivedTime, 10)).toISOString(),
      })),
    });
  } catch (err) {
    console.error("[Zoho] debug/process error:", err.message);
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
