-- 0215_whatsapp_user_level.sql
-- WhatsApp Business config, per-user: each CRM user connects their own
-- number from their own Meta app. Tenant admin/super admin never hold
-- numbers or secrets — they only gate/observe (see tenant_features
-- 'whatsapp' flag, added in 0214, and the read-only directory endpoints in
-- crm-whatsapp.js).
--
-- No unconditional DROPs here (an earlier version of this file had them,
-- meant to clear a briefly-lived prior tenant-level model) — this file's
-- filename collided across two merged branch histories (master's own
-- 0198-0215 numbering vs. develop's re-numbered 0216-0230), so an
-- environment can legitimately reach this migration with these exact
-- tables already present and correct: either from develop's own copy of
-- this migration under a different filename, or — for tenant_whatsapp_config
-- specifically — because later migrations (0231/0232, already applied and
-- filename-tracked, so they will NOT re-run after this one) already
-- reverted the schema back to tenant-level. A DROP here would destroy that
-- live, correct state with nothing left downstream to recreate it. Every
-- statement below is IF (NOT) EXISTS instead, so this migration is a
-- genuine no-op wherever the end state it describes doesn't apply.

CREATE TABLE IF NOT EXISTS whatsapp_configs (
  id                    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id             UUID        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  user_id               UUID        NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  waba_id               TEXT        NOT NULL,
  phone_number_id       TEXT        NOT NULL UNIQUE,
  display_phone_number  TEXT,
  access_token          TEXT        NOT NULL,
  app_secret            TEXT,
  webhook_verify_token  TEXT        NOT NULL,
  is_enabled            BOOLEAN     NOT NULL DEFAULT true,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_whatsapp_configs_tenant ON whatsapp_configs(tenant_id);

COMMENT ON TABLE  whatsapp_configs                     IS 'Per-user WhatsApp Business Cloud API config — each CRM user connects their own number from their own Meta app; tenant_id is kept only for tenant-scoped isolation/oversight, never a shared channel.';
COMMENT ON COLUMN whatsapp_configs.access_token        IS 'AES-256-GCM encrypted — use src/utils/encrypt.js to decrypt';
COMMENT ON COLUMN whatsapp_configs.app_secret           IS 'AES-256-GCM encrypted — use src/utils/encrypt.js to decrypt. Optional at setup, needed to verify webhook signatures.';
COMMENT ON COLUMN whatsapp_configs.webhook_verify_token IS 'AES-256-GCM encrypted — use src/utils/encrypt.js to decrypt. Generated by the CRM on connect; the user pastes it into their own Meta App webhook config.';

CREATE TABLE IF NOT EXISTS whatsapp_messages (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id        UUID        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  owner_user_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  lead_id          INTEGER     REFERENCES crm_leads(id) ON DELETE CASCADE,
  partner_id       UUID        REFERENCES crm_partners(id) ON DELETE CASCADE,
  direction        VARCHAR(10) NOT NULL CHECK (direction IN ('incoming', 'outgoing')),
  from_phone       TEXT        NOT NULL,
  to_phone         TEXT        NOT NULL,
  body             TEXT,
  meta_message_id  TEXT,
  status           VARCHAR(20) NOT NULL DEFAULT 'sent',
  raw_payload      JSONB,
  created_by       UUID        REFERENCES users(id) ON DELETE SET NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- The indexes below reference owner_user_id, a per-user-model-only column —
-- on an environment where whatsapp_messages already existed in the
-- (correct, later-reverted-to) per-tenant shape, CREATE TABLE IF NOT EXISTS
-- above was a no-op and this column was never added, so a plain CREATE
-- INDEX here would fail with "column does not exist". Only create them
-- when the column is actually present.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'whatsapp_messages' AND column_name = 'owner_user_id'
  ) THEN
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_whatsapp_messages_tenant ON whatsapp_messages(tenant_id)';
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_whatsapp_messages_owner ON whatsapp_messages(owner_user_id)';
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_whatsapp_messages_lead ON whatsapp_messages(lead_id) WHERE lead_id IS NOT NULL';
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_whatsapp_messages_partner ON whatsapp_messages(partner_id) WHERE partner_id IS NOT NULL';
    -- Guards against duplicate rows on Meta's at-least-once webhook retries.
    -- Scoped per owner_user_id (each user's own phone_number_id), tighter
    -- than the old per-tenant scoping since numbers are no longer shared
    -- in-tenant.
    EXECUTE 'CREATE UNIQUE INDEX IF NOT EXISTS idx_whatsapp_messages_meta_id ON whatsapp_messages(owner_user_id, meta_message_id) WHERE meta_message_id IS NOT NULL';
    EXECUTE $c$COMMENT ON TABLE whatsapp_messages IS 'Per-user WhatsApp conversation log. owner_user_id identifies whose connected number the message went through; lead_id/partner_id identify who it is with.'$c$;
    EXECUTE $c$COMMENT ON COLUMN whatsapp_messages.meta_message_id IS 'Meta Cloud API message id — used for delivery/read status webhooks and to deduplicate retried webhook deliveries.'$c$;
    EXECUTE $c$COMMENT ON COLUMN whatsapp_messages.raw_payload IS 'Raw webhook payload for incoming messages/status updates — not populated for outgoing sends.'$c$;
  END IF;
END $$;
