-- 0215_whatsapp_user_level.sql
-- Replaces the tenant-level WhatsApp model (0206/0207: one shared company
-- number per tenant, superadmin-only) with a per-user model: each CRM user
-- connects their own WhatsApp Business number from their own Meta app.
-- Tenant admin/super admin no longer hold numbers or secrets — they only
-- gate/observe (see tenant_features 'whatsapp' flag, added in 0214, and the
-- read-only directory endpoints in crm-whatsapp.js).
--
-- Dropped instead of altered: both tables only ever held throwaway test data
-- (one test tenant config, a handful of test messages), never deployed
-- beyond this branch, so there is nothing worth migrating forward.

DROP TABLE IF EXISTS whatsapp_messages;
DROP TABLE IF EXISTS tenant_whatsapp_config;

CREATE TABLE whatsapp_configs (
  id                    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id             UUID        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  user_id               UUID        NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  waba_id               TEXT        NOT NULL,
  phone_number_id       TEXT        NOT NULL UNIQUE,
  display_phone_number  TEXT,
  access_token          TEXT        NOT NULL,
  app_secret            TEXT,
  webhook_verify_token  TEXT        NOT NULL,
  is_enabled            BOOLEAN     NOT NULL DEFAULT true,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_whatsapp_configs_tenant ON whatsapp_configs(tenant_id);

COMMENT ON TABLE  whatsapp_configs                     IS 'Per-user WhatsApp Business Cloud API config — each CRM user connects their own number from their own Meta app; tenant_id is kept only for tenant-scoped isolation/oversight, never a shared channel.';
COMMENT ON COLUMN whatsapp_configs.access_token        IS 'AES-256-GCM encrypted — use src/utils/encrypt.js to decrypt';
COMMENT ON COLUMN whatsapp_configs.app_secret           IS 'AES-256-GCM encrypted — use src/utils/encrypt.js to decrypt. Optional at setup, needed to verify webhook signatures.';
COMMENT ON COLUMN whatsapp_configs.webhook_verify_token IS 'AES-256-GCM encrypted — use src/utils/encrypt.js to decrypt. Generated by the CRM on connect; the user pastes it into their own Meta App webhook config.';

CREATE TABLE whatsapp_messages (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id        UUID        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  owner_user_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  lead_id          INTEGER     REFERENCES crm_leads(id) ON DELETE CASCADE,
  partner_id       UUID        REFERENCES crm_partners(id) ON DELETE CASCADE,
  direction        VARCHAR(10) NOT NULL CHECK (direction IN ('incoming', 'outgoing')),
  from_phone       TEXT        NOT NULL,
  to_phone         TEXT        NOT NULL,
  body             TEXT,
  meta_message_id  TEXT,
  status           VARCHAR(20) NOT NULL DEFAULT 'sent',
  raw_payload      JSONB,
  created_by       UUID        REFERENCES users(id) ON DELETE SET NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_whatsapp_messages_tenant  ON whatsapp_messages(tenant_id);
CREATE INDEX idx_whatsapp_messages_owner   ON whatsapp_messages(owner_user_id);
CREATE INDEX idx_whatsapp_messages_lead    ON whatsapp_messages(lead_id)    WHERE lead_id IS NOT NULL;
CREATE INDEX idx_whatsapp_messages_partner ON whatsapp_messages(partner_id) WHERE partner_id IS NOT NULL;

-- Guards against duplicate rows on Meta's at-least-once webhook retries.
-- Scoped per owner_user_id (each user's own phone_number_id), tighter than
-- the old per-tenant scoping since numbers are no longer shared in-tenant.
CREATE UNIQUE INDEX idx_whatsapp_messages_meta_id
  ON whatsapp_messages(owner_user_id, meta_message_id) WHERE meta_message_id IS NOT NULL;

COMMENT ON TABLE whatsapp_messages IS 'Per-user WhatsApp conversation log. owner_user_id identifies whose connected number the message went through; lead_id/partner_id identify who it is with.';
COMMENT ON COLUMN whatsapp_messages.meta_message_id IS 'Meta Cloud API message id — used for delivery/read status webhooks and to deduplicate retried webhook deliveries.';
COMMENT ON COLUMN whatsapp_messages.raw_payload IS 'Raw webhook payload for incoming messages/status updates — not populated for outgoing sends.';
