-- 0235_invoices.sql
-- Billing module (M1): generated invoices + numbering sequence.
--
-- Numbering is GLOBAL per year (INV-2026-0001), not per-tenant like
-- doc_number_seq — these invoices have a single issuer (CRMtree) billing many
-- tenants, unlike `documents` where each tenant issues its own numbered docs.
-- Assumption, easy to revisit before this feeds real accounting (KSeF is
-- explicitly deferred per the 2026-08-03 meeting notes).

DO $$ BEGIN
  CREATE TYPE invoice_status AS ENUM ('issued', 'void');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS invoice_number_seq (
  year    SMALLINT PRIMARY KEY,
  last_n  INTEGER  NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS invoices (
  id                UUID               PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         UUID               NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  plan_id           UUID               NOT NULL REFERENCES billing_plans(id),
  invoice_number    VARCHAR(32),
  billing_cycle     billing_cycle_type NOT NULL,
  period_start      DATE               NOT NULL,
  period_end        DATE               NOT NULL,
  active_user_count INTEGER            NOT NULL,
  unit_price_eur    NUMERIC(10,2)      NOT NULL,
  total_amount_eur  NUMERIC(12,2)      NOT NULL,
  currency          CHAR(3)            NOT NULL DEFAULT 'EUR',
  status            invoice_status     NOT NULL DEFAULT 'issued',
  pdf_blob_path     TEXT,
  generated_at      TIMESTAMPTZ        NOT NULL DEFAULT now(),
  created_at        TIMESTAMPTZ        NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, period_start, period_end)
);

CREATE INDEX IF NOT EXISTS idx_invoices_tenant  ON invoices(tenant_id);
CREATE INDEX IF NOT EXISTS idx_invoices_period  ON invoices(period_start, period_end);

COMMENT ON TABLE invoices IS 'One row per billing period per tenant, generated by the billing-run batch (or void/replaced manually).';
COMMENT ON COLUMN invoices.active_user_count IS 'Distinct users with a user_login audit_logs event in [period_start, period_end].';
COMMENT ON CONSTRAINT invoices_tenant_id_period_start_period_end_key ON invoices IS 'Prevents the batch from double-billing the same tenant/period on a re-run.';

CREATE OR REPLACE FUNCTION generate_invoice_number()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  v_year SMALLINT := EXTRACT(YEAR FROM NEW.period_end);
  v_seq  INTEGER;
BEGIN
  INSERT INTO invoice_number_seq (year, last_n) VALUES (v_year, 1)
    ON CONFLICT (year) DO UPDATE SET last_n = invoice_number_seq.last_n + 1
    RETURNING last_n INTO v_seq;
  NEW.invoice_number := 'INV-' || v_year || '-' || LPAD(v_seq::TEXT, 4, '0');
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_generate_invoice_number ON invoices;
CREATE TRIGGER trg_generate_invoice_number
  BEFORE INSERT ON invoices
  FOR EACH ROW
  WHEN (NEW.invoice_number IS NULL)
  EXECUTE FUNCTION generate_invoice_number();
